/**
 * Downloadable PDF cheatsheets. The app is offline-first with no PDF library
 * bundled, so we generate a clean, print-styled HTML document and open it in a
 * new window with the browser's print dialog — "Save as PDF" produces a real
 * PDF on every platform, zero dependencies.
 */
import type { Guide } from './curriculum'

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
}

function cheatsheetHtml(guide: Guide): string {
  const rows = guide.cheatRows
    .map(
      (r) => `<tr>
        <td class="form">${escapeHtml(r.form)}</td>
        <td class="use">${escapeHtml(r.use)}</td>
        <td class="ex">${escapeHtml(r.example)}</td>
      </tr>`
    )
    .join('')

  const sections = guide.sections
    .map(
      (s) => `<section>
        <h2>${escapeHtml(s.heading)}</h2>
        ${s.body.map((b) => `<p>${escapeHtml(b)}</p>`).join('')}
        ${s.examples ? `<ul>${s.examples.map((e) => `<li>${escapeHtml(e)}</li>`).join('')}</ul>` : ''}
      </section>`
    )
    .join('')

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>${escapeHtml(guide.title)} — cheatsheet</title>
<style>
  @page { margin: 18mm; }
  * { box-sizing: border-box; }
  body { font-family: -apple-system, "Segoe UI", Roboto, Arial, sans-serif; color: #111; line-height: 1.5; max-width: 760px; margin: 0 auto; padding: 24px; }
  .brand { color: #2563EB; font-weight: 800; letter-spacing: .12em; text-transform: uppercase; font-size: 11px; }
  h1 { font-size: 28px; margin: 4px 0 2px; }
  .level { color: #555; font-size: 13px; margin-bottom: 4px; }
  .summary { color: #333; font-size: 14px; margin: 8px 0 20px; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 24px; font-size: 13px; }
  th { text-align: left; background: #f1f5ff; color: #1e3a8a; padding: 8px 10px; border-bottom: 2px solid #2563EB; }
  td { padding: 8px 10px; border-bottom: 1px solid #e5e7eb; vertical-align: top; }
  td.form { font-weight: 700; white-space: nowrap; }
  td.ex { color: #2563EB; font-style: italic; }
  section { margin-bottom: 16px; page-break-inside: avoid; }
  h2 { font-size: 16px; color: #1e3a8a; margin: 18px 0 6px; border-left: 3px solid #2563EB; padding-left: 8px; }
  p { margin: 4px 0; font-size: 13.5px; }
  ul { margin: 6px 0 6px 18px; }
  li { color: #2563EB; font-style: italic; font-size: 13px; margin: 2px 0; }
  footer { margin-top: 28px; color: #888; font-size: 11px; border-top: 1px solid #e5e7eb; padding-top: 8px; }
  @media print { body { padding: 0; } .noprint { display: none; } }
</style>
</head>
<body>
  <p class="brand">SpeakAI · Grammar cheatsheet</p>
  <h1>${escapeHtml(guide.title)}</h1>
  <p class="level">CEFR ${escapeHtml(guide.level)}</p>
  <p class="summary">${escapeHtml(guide.summary)}</p>
  <table>
    <thead><tr><th>Form</th><th>Use</th><th>Example</th></tr></thead>
    <tbody>${rows}</tbody>
  </table>
  ${sections}
  <footer>Generated by SpeakAI — your English learning companion.</footer>
  <script>window.onload = function () { setTimeout(function () { window.print(); }, 300); };</script>
</body>
</html>`
}

/**
 * Open the print-ready cheatsheet in a new window. The user picks
 * "Save as PDF" (or prints). Falls back to a Blob download if popups are
 * blocked so the action never silently fails.
 */
export function downloadCheatsheet(guide: Guide): void {
  const html = cheatsheetHtml(guide)
  const win = window.open('', '_blank', 'width=820,height=900')
  if (win) {
    win.document.open()
    win.document.write(html)
    win.document.close()
    return
  }
  // Popup blocked → download the HTML cheatsheet directly.
  const blob = new Blob([html], { type: 'text/html' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${guide.id}-cheatsheet.html`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
